name: gt
channels:
- defaults
dependencies:
- cycler=0.10.0=py36_0
- dbus=1.10.10=0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libiconv=1.14=0
- libpng=1.6.27=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=2.0.2=np112py36_0
- mkl=2017.0.1=0
- mpmath=0.19=py36_1
- numpy=1.12.1=py36_0
- openssl=1.0.2k=2
- pcre=8.39=1
- pip=9.0.1=py36_1
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- qt=5.6.2=4
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- sympy=1.0=py36_0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - axelrod==2.12.0
  - hypothesis==3.10.0
  - nashpy==0.0.4
  - prompt-toolkit==1.0.14
  - scipy==0.19.0
  - tqdm==4.11.2
  - wcwidth==0.1.7
prefix: /home/vince/anaconda3/envs/gt

